# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ApiDemo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  
  pod 'Alamofire'
  pod 'SwiftyJSON'
  pod 'SVProgressHUD'
  pod 'JJFloatingActionButton'
  pod 'FTPopOverMenu_Swift', '~> 0.0.6'

  # Pods for ApiDemo

  target 'ApiDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ApiDemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
